### ISSUE TITLE
More Features?

### ISSUE THREAD

**Issue by sohnkarlsruhe** [seikan/homebridge-xiaomi-mi-robot-vacuum#1]
More features like https://www.npmjs.com/package/homebridge-mi-robot-vacuum?
Please add config

**Comment by seikan** [comment]
Hi, the plugin has been updated with proper documentation.

And yes, this plugin has more features such as controlling the suction power, returning to charging dock.

**Comment by sohnkarlsruhe** [comment]
thanks for your work!
