### ISSUE TITLE
Pause (without returning to the dock).

### ISSUE THREAD

**Issue by UndisclosedBox83** [seikan/homebridge-xiaomi-mi-robot-vacuum#12]
Hello and thank you for the plugin. In my case, I have a large apartment and I would like to pause the robot in the middle of the cleaning to empty the bin and then continue cleaning the rest. Is there any way I can do that with your plugin or can you add that function? Right now, If I press the robot button in the Home app while it is cleaning, the robot will return to the dock. Thank you!

**Comment by seikan** [comment]
I will find a better solution to include in next release.

**Comment by seikan** [comment]
A pause "Switch" has been added.
