### ISSUE TITLE
Slider in 4 steps

### ISSUE THREAD

**Issue by Nastras** [seikan/homebridge-xiaomi-mi-robot-vacuum#13]
Hello, is it possible that you change slider for the stages in 4 steps 1-4?
I think that would be better to adjust as before in percent 0-100.

**Comment by wilkinsm89** [comment]
+1

**Comment by Nastras** [comment]
What do you mean with +1?

One more stage?

**Comment by wilkinsm89** [comment]
I would also like this

**Comment by Nastras** [comment]
Alright, I'm glad that you like the idea

**Comment by FezVrasta** [comment]
Is this even possible API wise? I couldn't understand if the fans can support steps in their sliders..

**Comment by Nastras** [comment]
@seikan what do you mean about the idea?
