### ISSUE TITLE
Connected but controls don't work

### ISSUE THREAD

**Issue by BillS11** [seikan/homebridge-xiaomi-mi-robot-vacuum#14]
I can see the vacuum cleaner in my Home app and can switch it on and off but the robot doesn't respond. Any ideas?

The error I'm getting is:
(node:1126) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Not able to initialize robot vacuum.
(node:1126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tonijj** [comment]
I was just about to report the same issue! 

It shows up in the Home app, but I get the same issue when starting Homebridge on my Raspberry Pi running Hassbian. 

Would love to understand what to do to fix this.

**Comment by FezVrasta** [comment]
I'm getting the same error on latest Raspbian

**Comment by jmaffie** [comment]
I have the same issue. Followed the installation instructions. Tried on Freenas server and on a Mac. 
Any Ideas?

**Comment by tonijj** [comment]
I solved it. Missed one little digit in the token. Had 31 digits, should be 32. So count them!
