### ISSUE TITLE
Unhandled Rejection Detected

### ISSUE THREAD

**Issue by 350d** [seikan/homebridge-xiaomi-mi-robot-vacuum#15]
I got this error on fresh Homebridge setup. I've tried to update token already - same result.

<img width="826" alt="screenshot 2018-01-23 01 30 55" src="https://user-images.githubusercontent.com/429208/35261197-230e7e84-ffdd-11e7-85cc-a254fea22339.png">

**Comment by 350d** [comment]
I've tried to reinstall `sudo npm install -g homebridge-xiaomi-mi-robot-vacuum miio` and now I have this:
````
Jan 25 02:36:17 pi3 homebridge[600]: [1/25/2018, 2:36:17 AM] [Mi Robot] Initializing MiRobotVacuum accessory...
Jan 25 02:36:18 pi3 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Jan 25 02:36:18 pi3 systemd[1]: homebridge.service: Unit entered failed state.
Jan 25 02:36:18 pi3 systemd[1]: homebridge.service: Failed with result 'exit-code'.
````

**Comment by seikan** [comment]
The issue has been resolved in latest version.
