### ISSUE TITLE
Send to Dock?

### ISSUE THREAD

**Issue by seppelicous** [seikan/homebridge-xiaomi-mi-robot-vacuum#17]
Hi,
Is it possible to Sent the robot back to dock when switching off via homekit?
Right now, the robot only pauses the work. 
Thanks in advance

**Comment by bertybassett** [comment]
same here.

Switch on = start 
same switch turned off = pause

Pause switch = nothing

**Comment by bertybassett** [comment]
could this be something to do with the fact I have a roborock Version 2  of the vacuum?

**Comment by bertybassett** [comment]
could the hex codes be different on the different models?  

@seppelicous what version of the vacuum do you have?

**Comment by seppelicous** [comment]
I have the roborock s50

**Comment by Bankaifan** [comment]
It is a problem with the new firmware. We all have to wait for the Miio-Plugin-Update

**Comment by patwae** [comment]
I've the same problem. Does anybody know if it's possible to downgrade the rockrobo software, until this problem get fixed?

Thanks!

**Comment by patwae** [comment]
I have just seen that the new update (0.1.3) is available for download. I have already installed it and it works without any problems.
@seikan: Thanks a lot for this!

**Comment by seppelicous** [comment]
Which software has to be updated?

**Comment by patwae** [comment]
At this moment, you have to update your Xiaomi Mi Robot to the newest software and get the new update of the homebridge plugin (0.1.3). Then the robot will go back to the dock, if you turn off the switch in homekit.

**Comment by bertybassett** [comment]
not seeing plugin (0.1.3) how do I get that?

**Comment by seppelicous** [comment]
Which plugin do you mean? This Plugin is t 1.1.0 and it is the only plugin I have installed.

**Comment by seppelicous** [comment]
Do you mean this plugin: https://github.com/YinHangCode/homebridge-mi-robot_vacuum ?

**Comment by seikan** [comment]
The latest version will return dock when you stopped the robot. There is another "Switch" added where you can just pause the robot.
