### ISSUE TITLE
Error (node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6)

### ISSUE THREAD

**Issue by th3cube** [seikan/homebridge-xiaomi-mi-robot-vacuum#2]
Hi Seikan,

i successfully got the token and configured the plugin. Vacuum Cleaner Shows up in Homekit as a Fan but when i try to start it nothing happens. Hombridge logfile drops an error massage 

"(node:194) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Call to device timed out"

after a while Homebridge crashes.

Im using the latest versions.

**Comment by th3cube** [comment]
i read out the token once again and now it works. Every time u reset the Device the token changes...

THX for this nice Plugin!

**Comment by philboycn** [comment]
OK ,same wrong message here ,i didn't reset the robot and the read out again is also not working.i think it is not about the token...
