### ISSUE TITLE
Token Extraction

### ISSUE THREAD

**Issue by jungopro** [seikan/homebridge-xiaomi-mi-robot-vacuum#20]
Hi
I can’t get the token using miio since I have a new firmware.
I downgraded the firmware and was able to get the token but once I did a firmware upgrade the plugin stopped working

Anyway to get the token and stay with the latest firmware?

Thanks
Omer

**Comment by 350d** [comment]
`miio` method doesn't work for me too. iOS method works fine https://www.home-assistant.io/components/vacuum.xiaomi_miio/

**Comment by seikan** [comment]
Thanks for the update. For Android, it seems like you need to downgrade the Mi Home app to get the token now.

**Comment by jungopro** [comment]
Hi @350d, the iOS method worked for me. Thank you
However, I don't get the plugin's full functionality. I can turn it on / off and set the suction power, but I don't see battery level or charging state... any idea how to get it working?
