### ISSUE TITLE
Can't connect to Xiaomi Robot

### ISSUE THREAD

**Issue by ghost** [seikan/homebridge-xiaomi-mi-robot-vacuum#5]
Hello all,

Unfortunately this plugin doesn't work for me. I've set up everything according to the manual. The fan-icon is showed in the app but when I press the button all I get is:

Jun 18 21:01:58 homebridge homebridge[855]: (node:855) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Call to device timed out
Jun 18 21:01:58 homebridge homebridge[855]: (node:855) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Call to device timed out

I'm running the latest Node.js (8.1.2). Your plugin is up-to-date. The vaccum-cleaner runs with version 3.39_003074

What can I do in order to get this running?

Thank you very much!

**Comment by philboycn** [comment]
Find solution here: https://github.com/aholstenson/miio/issues/40

**Comment by ghost** [comment]
Thank you, works like a charm now. :)

**Comment by ghost** [comment]
I made a backup of my iPhone and from the Mi-Home sql-file I got a different token than in the description of this plugin. This works.
