### ISSUE TITLE
Call to device time out

### ISSUE THREAD

**Issue by hipudding** [seikan/homebridge-xiaomi-mi-robot-vacuum#7]
I followed your introduce step by step, but my homebridge report an error.

(node:461) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Not able to initialize robot vacuum.
(node:461) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:461) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Call to device timed out

**Comment by seikan** [comment]
May I know what version of Node JS you have installed? Make sure you have Node 6 and above installed.

If you still not able to get the token, you may follow the instructions by https://github.com/seikan/homebridge-xiaomi-mi-robot-vacuum/issues/3#issuecomment-317495544

**Comment by Tim2309** [comment]
Hello I was able to get the token but have the same problem:

(node:1266) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Not able to initialize robot vacuum.

(node:1240) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Call to device timed out

ping to the robot ip works

**Comment by seikan** [comment]
What is your Node version? Please make sure you have NodeJS 6 or above installed.

**Comment by Tim2309** [comment]
my version is 6.10.0

**Comment by seikan** [comment]
@Tim2309 I'm sorry, it seems like is a problem from miIO library. May I know which version of miIO you have installed as well? Due to recent firmware update from Mi, the setup have not working perfectly now.

**Comment by Tim2309** [comment]
My Robot is on 3.3.9_003077 If this help

How can i Check my milO Version?

**Comment by Tim2309** [comment]
do you mean miio?
I got the version number from the package.json its miio@0.13.0

the problem was a false token, i used an android phone and the mi toolkit to get the right one.

**Comment by CrazyMouse** [comment]
@seikan any plan to fix the bug? thanks

**Comment by hipudding** [comment]
@seikan My Nodejs version is 7.

**Comment by hipudding** [comment]
@Tim2309 Hi, do you mean the guide of miio to get the token cannot get a right one? How to use an android phone to get token? Install mihome and try developer mode?

**Comment by Tim2309** [comment]
I used an android and the mi toolkit
https://github.com/ultrara1n/MiToolkit/releases

All other methods didn‘t work for me (iPhone backup and Terminal command)

**Comment by hipudding** [comment]
@Tim2309 thx

**Comment by siavashvj** [comment]
The token never comes. Been waiting 20 min now. I'm on Node.js v 6, via Terminal/Mac OS.

**Comment by siavashvj** [comment]
Allright, just managed to get the Token, however I got the same error: 

`(node:5851) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Call to device timed out`

**Comment by matphillips** [comment]
I got the token easily, almost instantly in fact, but no control over the vacuum and the same Unhandled promise rejection as being reported here.
Node version 7.10.1
Miio: 0.13.0
homebridge-xiaomi-mi-robot-vacuum: 1.1.0

Vacuum has static DHCP assignment and the correct IP address is listed in the config.json

**Comment by Luftloch80** [comment]
Same Problem with node 6.11 
Earlier there was no Problem
Could also be ios 11 Problem

**Comment by Kiter1988** [comment]
Same Problem here 

`(node:1309) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Not able to initialize robot vacuum.`

**Comment by Kiter1988** [comment]
@seikan , can you solve that problem ? 

Edit: It's 23:37 , and the robots works again with homekit =) 
I dont know why

**Comment by adidoes** [comment]
I still have this issue, any ideas?

**Comment by seikan** [comment]
@adidoes What error message you got?

**Comment by adidoes** [comment]
I get this:

```
homebridge > (node:9998) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Call to device timed out
homebridge > (node:9998) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Call to device timed out
```

also this:

```
(node:10746) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Not able to initialize robot vacuum.
(node:10746) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Funny thing is that trying to reproduce this it worked once, but I have no idea why.

**Comment by Bankaifan** [comment]
Solution for me was the description postet by @Nastra888 in #3 

> 
> Hello, here is the solution for iOS decrypting the 92-digit token under variant 1, step 7.
> 
> http://forum.smartapfel.de/forum/thread/370-saugroboter-xiaomi-mi-robot-vacuum-token-auslesen/?postID=7021#post7021

**Comment by conorlmcbride** [comment]
I am also getting "Call to device timed out" errors. Here are a few.

node: 9.3.0
I'm trying to run this on a raspberry pi zero w (armv6) but the rest of homebridge and other node programs seem to be working correctly.


`(node:28589) UnhandledPromiseRejectionWarning: Error: Not able to initialize robot vacuum.
    at /home/pi/.nvm/versions/node/v9.3.0/lib/node_modules/homebridge-xiaomi-mi-robot-vacuum/index.js:83:11
    at <anonymous>
(node:28589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28589) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28589) UnhandledPromiseRejectionWarning: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/home/pi/.nvm/versions/node/v9.3.0/lib/node_modules/miio/lib/device.js:225:18)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
(node:28589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:28589) UnhandledPromiseRejectionWarning: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/home/pi/.nvm/versions/node/v9.3.0/lib/node_modules/miio/lib/device.js:225:18)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
(node:28589) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)`

**Comment by seikan** [comment]
Please update to latest version of miio.
